In [1]:
import pandas as pd
import json
from pathlib import Path

RAW = Path("../data/raw")

edges = pd.read_csv(RAW / "IRN_edges.csv")
delays = pd.read_csv(RAW / "train_routes_delays_Sep2024.csv")
routes = pd.read_csv(RAW / "train_routes_Sep2024.csv")

with open(RAW / "stations_zones_mapping.json", "r", encoding="utf-8") as f:
    station_zones = json.load(f)

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [2]:
print("========== DATASET SIZES ==========")

print("Network edges:", edges.shape)
print("Train delays:", delays.shape)
print("Train routes:", routes.shape)
print("Station-zone mappings:", len(station_zones))

========== DATASET SIZES ==========
Network edges: (9336, 4)
Train delays: (1282325, 9)
Train routes: (85055, 8)
Station-zone mappings: 4735

In [3]:
print("========== COLUMNS ==========")

print("\nTRAIN DELAYS:")
print(delays.columns.tolist())

print("\nTRAIN ROUTES:")
print(routes.columns.tolist())

print("\nNETWORK EDGES:")
print(edges.columns.tolist())

========== COLUMNS ==========

TRAIN DELAYS:
['train', 'date', 'station', 'sch_arr', 'act_arr', 'arr_delay', 'sch_dep', 'act_dep', 'dep_delay']

TRAIN ROUTES:
['stnSerialNumber', 'trainNumber', 'trainName', 'station_code', 'station_name', 'distance', 'arrivalTime', 'departureTime']

NETWORK EDGES:
['from', 'to', 'distance', 'ntrains']

In [4]:
print("========== SAMPLE DATA ==========")

print("\nTRAIN DELAYS:")
display(delays.head())

print("\nTRAIN ROUTES:")
display(routes.head())

print("\nNETWORK EDGES:")
display(edges.head())

========== SAMPLE DATA ==========

TRAIN DELAYS:

,train,date,station,sch_arr,act_arr,arr_delay,sch_dep,act_dep,dep_delay
0,12303,2024-09-02,HWH,08:00 AM,08:01 AM,0.0,08:00 AM,08:01 AM,0.0
1,12303,2024-09-02,BWN,09:05 AM,09:20 AM,15.0,09:08 AM,09:23 AM,15.0
2,12303,2024-09-02,DGR,09:57 AM,10:00 AM,3.0,09:59 AM,10:02 AM,3.0
3,12303,2024-09-02,ASN,10:32 AM,10:34 AM,2.0,10:37 AM,10:39 AM,2.0
4,12303,2024-09-02,CRJ,11:00 AM,11:04 AM,4.0,11:02 AM,11:06 AM,4.0

TRAIN ROUTES:

,stnSerialNumber,trainNumber,trainName,station_code,station_name,distance,arrivalTime,departureTime
0,1,12303,Poorva Express,HWH,Howrah,0,08:00 AM,08:00 AM
1,2,12303,Poorva Express,BWN,Bardhaman,95,09:05 AM,09:08 AM
2,3,12303,Poorva Express,DGR,Durgapur,157,09:57 AM,09:59 AM
3,4,12303,Poorva Express,ASN,Asansol,199,10:32 AM,10:37 AM
4,5,12303,Poorva Express,CRJ,Chittaranjan,224,11:00 AM,11:02 AM

NETWORK EDGES:

   from    to  distance  ntrains
0  AADR   UHL        28       10
1  AADR  DLPC        15        6
2   AAG   WKA         6        1
3   AAG  MKPT         7        1
4   AAL   BUH         9       14

In [5]:
print("========== DATA TYPES ==========")
print(delays.dtypes)

print("\n========== MISSING VALUES ==========")
print(delays.isnull().sum())

print("\n========== DUPLICATES ==========")
print("Duplicate rows:", delays.duplicated().sum())

print("\n========== UNIQUE VALUES ==========")
print("Unique trains:", delays["train"].nunique())
print("Unique stations:", delays["station"].nunique())
print("Unique dates:", delays["date"].nunique())

print("\n========== DATE RANGE ==========")
print("First date:", delays["date"].min())
print("Last date:", delays["date"].max())

========== DATA TYPES ==========
train          int64
date          object
station       object
sch_arr       object
act_arr       object
arr_delay    float64
sch_dep       object
act_dep       object
dep_delay    float64
dtype: object

========== MISSING VALUES ==========
train        0
date         0
station      0
sch_arr      0
act_arr      0
arr_delay    0
sch_dep      0
act_dep      0
dep_delay    0
dtype: int64

========== DUPLICATES ==========
Duplicate rows: 0

========== UNIQUE VALUES ==========
Unique trains: 3892
Unique stations: 4736
Unique dates: 30

========== DATE RANGE ==========
First date: 2024-09-01
Last date: 2024-09-30

In [6]:
print("========== DELAY STATISTICS ==========")

print(delays[["arr_delay", "dep_delay"]].describe())

========== DELAY STATISTICS ==========
          arr_delay     dep_delay
count  1.282325e+06  1.282325e+06
mean   3.289657e+01  3.289657e+01
std    8.452010e+01  8.452010e+01
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    8.000000e+00  8.000000e+00
75%    2.800000e+01  2.800000e+01
max    4.336000e+03  4.336000e+03

In [7]:
print("========== NEGATIVE DELAYS ==========")

print("Arrival delays < 0:", (delays["arr_delay"] < 0).sum())
print("Departure delays < 0:", (delays["dep_delay"] < 0).sum())

print("\nMost negative arrival delays:")
print(delays.nsmallest(10, "arr_delay")[["train", "date", "station", "arr_delay"]])

========== NEGATIVE DELAYS ==========
Arrival delays < 0: 0
Departure delays < 0: 0

Most negative arrival delays:
    train        date station  arr_delay
0   12303  2024-09-02     HWH        0.0
7   12303  2024-09-02    JSME        0.0
8   12303  2024-09-02     JAJ        0.0
18  12303  2024-09-02     DDU        0.0
24  12303  2024-09-02    NDLS        0.0
37  12303  2024-09-03    BARH        0.0
52  12303  2024-09-06     DGR        0.0
53  12303  2024-09-06     ASN        0.0
55  12303  2024-09-06     JMT        0.0
58  12303  2024-09-06     JAJ        0.0

In [8]:
print("========== SAMPLE TIME VALUES ==========")

print("Scheduled arrival:")
print(delays["sch_arr"].head(20).tolist())

print("\nActual arrival:")
print(delays["act_arr"].head(20).tolist())

print("\nScheduled departure:")
print(delays["sch_dep"].head(20).tolist())

print("\nActual departure:")
print(delays["act_dep"].head(20).tolist())

========== SAMPLE TIME VALUES ==========
Scheduled arrival:
['08:00 AM', '09:05 AM', '09:57 AM', '10:32 AM', '11:00 AM', '11:15 AM', '11:44 AM', '12:11 PM', '01:12 PM', '01:33 PM', '01:58 PM', '02:29 PM', '02:46 PM', '03:03 PM', '04:00 PM', '04:23 PM', '04:52 PM', '05:40 PM', '07:30 PM', '09:40 PM']

Actual arrival:
['08:01 AM', '09:20 AM', '10:00 AM', '10:34 AM', '11:04 AM', '11:17 AM', '11:46 AM', '12:11 PM', '01:12 PM', '01:37 PM', '02:09 PM', '02:56 PM', '03:20 PM', '03:37 PM', '04:22 PM', '04:46 PM', '05:15 PM', '06:01 PM', '07:31 PM', '09:43 PM']

Scheduled departure:
['08:00 AM', '09:08 AM', '09:59 AM', '10:37 AM', '11:02 AM', '11:17 AM', '11:46 AM', '12:15 PM', '01:17 PM', '01:35 PM', '02:00 PM', '02:31 PM', '02:48 PM', '03:05 PM', '04:10 PM', '04:25 PM', '04:57 PM', '05:42 PM', '07:40 PM', '09:45 PM']

Actual departure:
['08:01 AM', '09:23 AM', '10:02 AM', '10:39 AM', '11:06 AM', '11:19 AM', '11:48 AM', '12:15 PM', '01:17 PM', '01:39 PM', '02:11 PM', '02:58 PM', '03:22 PM', '03:39 PM', '04:32 PM', '04:48 PM', '05:20 PM', '06:03 PM', '07:41 PM', '09:48 PM']

In [9]:
# ==========================================
# STEP 3: JOURNEY RECONSTRUCTION
# ==========================================

# Make copies so the raw data remains untouched
d = delays.copy()
r = routes.copy()

# Convert train/date identifiers to consistent types
d["train"] = d["train"].astype(str)
r["trainNumber"] = r["trainNumber"].astype(str)
d["date"] = d["date"].astype(str)

# Sort route stops in journey order
r = r.sort_values(["trainNumber", "stnSerialNumber"])

# Create station sequence lookup
route_sequence = r[
    ["trainNumber", "station_code", "stnSerialNumber", "distance"]
].drop_duplicates()

# Merge sequence information into delay observations
journey = d.merge(
    route_sequence,
    left_on=["train", "station"],
    right_on=["trainNumber", "station_code"],
    how="left"
)

print("Journey table created.")
print("Rows:", len(journey))
print("Columns:", journey.columns.tolist())

Journey table created.
Rows: 1283395
Columns: ['train', 'date', 'station', 'sch_arr', 'act_arr', 'arr_delay', 'sch_dep', 'act_dep', 'dep_delay', 'trainNumber', 'station_code', 'stnSerialNumber', 'distance']

In [10]:
print("========== JOURNEY RECONSTRUCTION CHECK ==========")

print("Rows with missing station sequence:",
      journey["stnSerialNumber"].isna().sum())

print("Rows with missing distance:",
      journey["distance"].isna().sum())

print("\nSample reconstructed data:")
display(
    journey[
        [
            "train",
            "date",
            "station",
            "stnSerialNumber",
            "distance",
            "arr_delay",
            "dep_delay"
        ]
    ].head(15)
)

========== JOURNEY RECONSTRUCTION CHECK ==========
Rows with missing station sequence: 62
Rows with missing distance: 62

Sample reconstructed data:

    train        date station  stnSerialNumber  distance  arr_delay  dep_delay
0   12303  2024-09-02     HWH              1.0       0.0        0.0        0.0
1   12303  2024-09-02     BWN              2.0      95.0       15.0       15.0
2   12303  2024-09-02     DGR              3.0     157.0        3.0        3.0
3   12303  2024-09-02     ASN              4.0     199.0        2.0        2.0
4   12303  2024-09-02     CRJ              5.0     224.0        4.0        4.0
5   12303  2024-09-02     JMT              6.0     239.0        2.0        2.0
6   12303  2024-09-02     MDP              7.0     281.0        2.0        2.0
7   12303  2024-09-02    JSME              8.0     310.0        0.0        0.0
8   12303  2024-09-02     JAJ              9.0     354.0        0.0        0.0
9   12303  2024-09-02     JMU             10.0     380.0        4.0        4.0
10  12303  2024-09-02    KIUL             11.0     408.0       11.0       11.0
11  12303  2024-09-02     MKA             12.0     442.0       27.0       27.0
12  12303  2024-09-02    BARH             13.0     468.0       34.0       34.0
13  12303  2024-09-02     BKP             14.0     486.0       34.0       34.0
14  12303  2024-09-02    PNBE             15.0     531.0       22.0       22.0

In [11]:
# Check how many unique stops each train has
stops_per_train = (
    journey.groupby("train")["stnSerialNumber"]
    .nunique()
)

print("========== ROUTE LENGTH ==========")
print(stops_per_train.describe())

print("\nShortest routes:")
print(stops_per_train.nsmallest(10))

print("\nLongest routes:")
print(stops_per_train.nlargest(10))

========== ROUTE LENGTH ==========
count    3892.000000
mean       21.853546
std        12.946746
min         2.000000
25%        12.000000
50%        19.000000
75%        28.000000
max       119.000000
Name: stnSerialNumber, dtype: float64

Shortest routes:
train
12275    2
12276    2
52966    2
7359     2
12265    3
12266    3
12451    3
12452    3
1595     3
1596     3
Name: stnSerialNumber, dtype: int64

Longest routes:
train
13031    119
18237     90
13352     87
15909     86
15910     86
19037     86
19038     86
14030     85
11058     84
18238     83
Name: stnSerialNumber, dtype: int64

In [12]:
sample_train = journey[journey["train"] == "12303"].copy()

sample_train = sample_train.sort_values(
    ["date", "stnSerialNumber"]
)

display(
    sample_train[
        [
            "train",
            "date",
            "station",
            "stnSerialNumber",
            "sch_arr",
            "act_arr",
            "arr_delay",
            "sch_dep",
            "act_dep",
            "dep_delay"
        ]
    ].head(30)
)

,train,date,station,stnSerialNumber,sch_arr,act_arr,arr_delay,sch_dep,act_dep,dep_delay
0,12303,2024-09-02,HWH,1.0,08:00 AM,08:01 AM,0.0,08:00 AM,08:01 AM,0.0
1,12303,2024-09-02,BWN,2.0,09:05 AM,09:20 AM,15.0,09:08 AM,09:23 AM,15.0
2,12303,2024-09-02,DGR,3.0,09:57 AM,10:00 AM,3.0,09:59 AM,10:02 AM,3.0
3,12303,2024-09-02,ASN,4.0,10:32 AM,10:34 AM,2.0,10:37 AM,10:39 AM,2.0
4,12303,2024-09-02,CRJ,5.0,11:00 AM,11:04 AM,4.0,11:02 AM,11:06 AM,4.0
5,12303,2024-09-02,JMT,6.0,11:15 AM,11:17 AM,2.0,11:17 AM,11:19 AM,2.0
6,12303,2024-09-02,MDP,7.0,11:44 AM,11:46 AM,2.0,11:46 AM,11:48 AM,2.0
7,12303,2024-09-02,JSME,8.0,12:11 PM,12:11 PM,0.0,12:15 PM,12:15 PM,0.0
8,12303,2024-09-02,JAJ,9.0,01:12 PM,01:12 PM,0.0,01:17 PM,01:17 PM,0.0
9,12303,2024-09-02,JMU,10.0,01:33 PM,01:37 PM,4.0,01:35 PM,01:39 PM,4.0
10,12303,2024-09-02,KIUL,11.0,01:58 PM,02:09 PM,11.0,02:00 PM,02:11 PM,11.0
11,12303,2024-09-02,MKA,12.0,02:29 PM,02:56 PM,27.0,02:31 PM,02:58 PM,27.0
12,12303,2024-09-02,BARH,13.0,02:46 PM,03:20 PM,34.0,02:48 PM,03:22 PM,34.0
13,12303,2024-09-02,BKP,14.0,03:03 PM,03:37 PM,34.0,03:05 PM,03:39 PM,34.0
14,12303,2024-09-02,PNBE,15.0,04:00 PM,04:22 PM,22.0,04:10 PM,04:32 PM,22.0
15,12303,2024-09-02,DNR,16.0,04:23 PM,04:46 PM,23.0,04:25 PM,04:48 PM,23.0
16,12303,2024-09-02,ARA,17.0,04:52 PM,05:15 PM,23.0,04:57 PM,05:20 PM,23.0
17,12303,2024-09-02,BXR,18.0,05:40 PM,06:01 PM,21.0,05:42 PM,06:03 PM,21.0
18,12303,2024-09-02,DDU,19.0,07:30 PM,07:31 PM,0.0,07:40 PM,07:41 PM,0.0
19,12303,2024-09-02,PRYJ,20.0,09:40 PM,09:43 PM,3.0,09:45 PM,09:48 PM,3.0
20,12303,2024-09-02,CNB,21.0,12:02 AM,12:28 AM,26.0,12:07 AM,12:33 AM,26.0
21,12303,2024-09-02,ETW,22.0,01:29 AM,02:16 AM,47.0,01:31 AM,02:18 AM,47.0
22,12303,2024-09-02,TDL,23.0,02:48 AM,03:12 AM,24.0,02:50 AM,03:14 AM,24.0
23,12303,2024-09-02,ALJN,24.0,03:38 AM,04:00 AM,22.0,03:40 AM,04:02 AM,22.0
24,12303,2024-09-02,NDLS,25.0,06:05 AM,06:05 AM,0.0,06:05 AM,06:05 AM,0.0
25,12303,2024-09-03,HWH,1.0,08:00 AM,08:02 AM,2.0,08:00 AM,08:02 AM,2.0
26,12303,2024-09-03,BWN,2.0,09:05 AM,09:15 AM,10.0,09:08 AM,09:18 AM,10.0
27,12303,2024-09-03,DGR,3.0,09:57 AM,10:19 AM,22.0,09:59 AM,10:21 AM,22.0
28,12303,2024-09-03,ASN,4.0,10:32 AM,11:31 AM,59.0,10:37 AM,11:36 AM,59.0
29,12303,2024-09-03,CRJ,5.0,11:00 AM,12:22 PM,82.0,11:02 AM,12:24 PM,82.0

In [13]:
# ==========================================
# STEP 4: INVESTIGATE UNMATCHED STATIONS
# ==========================================

missing_sequence = journey[journey["stnSerialNumber"].isna()].copy()

print("Unmatched observations:", len(missing_sequence))

display(
    missing_sequence[
        ["train", "date", "station", "arr_delay", "dep_delay"]
    ].head(30)
)

Unmatched observations: 62

        train        date station  arr_delay  dep_delay
231704  13212  2024-09-01     TMA        0.0        0.0
231721  13212  2024-09-02     TMA        0.0        0.0
231738  13212  2024-09-03     TMA        0.0        0.0
231755  13212  2024-09-04     TMA        0.0        0.0
231772  13212  2024-09-05     TMA        0.0        0.0
231789  13212  2024-09-06     TMA        0.0        0.0
231806  13212  2024-09-07     TMA        0.0        0.0
231823  13212  2024-09-08     TMA        0.0        0.0
231840  13212  2024-09-09     TMA        0.0        0.0
231857  13212  2024-09-10     TMA        0.0        0.0
231874  13212  2024-09-11     TMA        0.0        0.0
231891  13212  2024-09-12     TMA        0.0        0.0
231908  13212  2024-09-13     TMA        0.0        0.0
231925  13212  2024-09-14     TMA        0.0        0.0
231942  13212  2024-09-15     TMA        0.0        0.0
231959  13212  2024-09-16     TMA        0.0        0.0
231976  13212  2024-09-17     TMA        0.0        0.0
231993  13212  2024-09-18     TMA        0.0        0.0
232010  13212  2024-09-19     TMA        0.0        0.0
232027  13212  2024-09-20     TMA        0.0        0.0
232044  13212  2024-09-21     TMA        0.0        0.0
232061  13212  2024-09-22     TMA        0.0        0.0
232078  13212  2024-09-23     TMA        0.0        0.0
232095  13212  2024-09-24     TMA        0.0        0.0
232112  13212  2024-09-25     TMA        0.0        0.0
232129  13212  2024-09-26     TMA        0.0        0.0
232146  13212  2024-09-27     TMA        0.0        0.0
232163  13212  2024-09-28     TMA        0.0        0.0
232180  13212  2024-09-29     TMA        0.0        0.0
232197  13212  2024-09-30     TMA        0.0        0.0

In [14]:
print("Unique unmatched station codes:")
print(missing_sequence["station"].unique())

print("\nNumber of unmatched observations by station:")
print(
    missing_sequence["station"]
    .value_counts()
    .head(30)
)

Unique unmatched station codes:
['TMA' 'KSG' 'KWP' 'OGL']

Number of unmatched observations by station:
station
TMA    30
KSG    26
KWP     3
OGL     3
Name: count, dtype: int64

In [15]:
print("========== UNMATCHED TRAINS ==========")

print(
    missing_sequence["train"]
    .value_counts()
    .head(30)
)

========== UNMATCHED TRAINS ==========
train
13212    30
20978    26
20952     3
4718      3
Name: count, dtype: int64

In [16]:
# ==========================================
# STEP 5: INVESTIGATE ROUTE MISMATCHES
# ==========================================

problem_trains = ["13212", "20978", "20952", "4718"]

for train_id in problem_trains:
    print("\n" + "=" * 60)
    print("TRAIN:", train_id)

    train_route = routes[
        routes["trainNumber"].astype(str) == train_id
    ].sort_values("stnSerialNumber")

    print("Route stations:")
    display(
        train_route[
            [
                "stnSerialNumber",
                "station_code",
                "station_name",
                "distance",
                "arrivalTime",
                "departureTime"
            ]
        ]
    )

============================================================
TRAIN: 13212
Route stations:

,stnSerialNumber,station_code,station_name,distance,arrivalTime,departureTime
15393,1,DNR,Danapur,0,06:10 AM,06:10 AM
15394,2,PPTA,Patliputra,6,06:25 AM,06:30 AM
15395,3,HJP,Hajipur,26,07:10 AM,07:15 AM
15396,4,MFP,Muzaffarpur,80,08:10 AM,08:15 AM
15397,5,SPJ,Samastipur,132,09:30 AM,10:00 AM
15398,6,DBG,Darbhanga,169,11:05 AM,11:10 AM
15399,7,SKI,Sakri,189,11:28 AM,11:30 AM
15400,8,JJP,Jhanjharpur,208,12:01 PM,12:03 PM
15401,9,GGH,Ghogardiha,229,12:21 PM,12:23 PM
15402,10,NMA,Nirmali,245,12:33 PM,12:35 PM
15403,11,SRGR,Saraygarh,264,12:58 PM,01:00 PM
15404,12,RGV,Raghopur,275,01:10 PM,01:12 PM
15405,13,LLP,Lalitgram,295,01:40 PM,02:10 PM
15406,14,NPV,Narpatganj,306,02:23 PM,02:25 PM
15407,15,FBG,Forbesganj,323,03:05 PM,03:25 PM
15408,16,JBN,Jogbani,337,03:45 PM,03:45 PM

============================================================
TRAIN: 20978
Route stations:

,stnSerialNumber,station_code,station_name,distance,arrivalTime,departureTime
36820,1,CDG,Chandigarh,0,03:15 PM,03:15 PM
36821,2,UMB,Ambala Cant,45,03:53 PM,03:55 PM
36822,3,DEC,Delhi Cantt,248,06:23 PM,06:33 PM
36823,4,GGN,Gurgaon,265,06:53 PM,06:55 PM
36824,5,RE,Rewari,317,07:38 PM,07:40 PM
36825,6,AWR,Alwar,391,08:22 PM,08:24 PM
36826,7,GADJ,Gandhinagar Jaipur,536,09:53 PM,09:55 PM
36827,8,JP,Jaipur,541,10:05 PM,10:10 PM
36828,9,AII,Ajmer,675,11:55 PM,11:55 PM

============================================================
TRAIN: 20952
Route stations:

,stnSerialNumber,station_code,station_name,distance,arrivalTime,departureTime
39010,1,JP,Jaipur,0,05:30 PM,05:40 PM
39011,2,FL,Phulera,55,06:23 PM,06:25 PM
39012,3,KSG,Kishangarh,109,07:04 PM,07:06 PM
39013,4,AII,Ajmer,134,07:50 PM,08:05 PM
39014,5,BER,Beawar,186,08:41 PM,08:43 PM
39015,6,SOD,Sojat Road,253,09:30 PM,09:32 PM
39016,7,MJ,Marwar,274,10:05 PM,10:10 PM
39017,8,FA,Falna,340,10:55 PM,10:57 PM
39018,9,JWB,Jawai Bandh,356,11:10 PM,11:12 PM
39019,10,ABR,Abu Road,439,12:25 AM,12:35 AM
39020,11,PNU,Palanpur,492,01:25 AM,01:27 AM
39021,12,SID,Siddhpur,521,01:51 AM,01:53 AM
39022,13,MSH,Mahesana,557,02:28 AM,02:30 AM
39023,14,VG,Viramgam,621,03:30 AM,03:32 AM
39024,15,SUNR,Surendranagar,686,04:36 AM,04:38 AM
39025,16,RJT,Rajkot,802,06:15 AM,06:25 AM
39026,17,HAPA,Hapa,875,07:30 AM,07:32 AM
39027,18,JAM,Jamnagar,884,07:44 AM,07:49 AM
39028,19,KMBL,Khambhaliya,938,08:37 AM,08:39 AM
39029,20,DWK,Dwarka,1022,09:59 AM,10:04 AM
39030,21,OKHA,Okha,1051,11:50 AM,11:50 AM

============================================================
TRAIN: 4718
Route stations:

,stnSerialNumber,station_code,station_name,distance,arrivalTime,departureTime
56830,1,TPTY,Tirupati,0,11:45 PM,11:45 PM
56831,2,RU,Renigunta,10,12:06 AM,12:08 AM
56832,3,GDR,Gudur,93,01:23 AM,01:25 AM
56833,4,NLR,Nellore,131,01:53 AM,01:55 AM
56834,5,BZA,Vijayawada,386,07:10 AM,07:20 AM
56835,6,KMT,Khammam,486,09:28 AM,09:30 AM
56836,7,WL,Warangal,595,10:18 AM,10:20 AM
56837,8,SKZR,Sirpur Kaghaznagar,768,02:38 PM,02:40 PM
56838,9,BPQ,Balharshah,838,03:55 PM,04:00 PM
56839,10,NGP,Nagpur,1047,07:15 PM,07:20 PM
56840,11,ET,Itarsi,1342,01:35 AM,01:40 AM
56841,12,BPL,Bhopal,1434,03:15 AM,03:25 AM
56842,13,SHRN,Sant Hirdaram Nagar,1446,03:48 AM,03:50 AM
56843,14,SJP,Shujalpur,1517,04:29 AM,04:31 AM
56844,15,UJN,Ujjain,1620,06:40 AM,06:45 AM
56845,16,NAD,Nagda,1675,07:55 AM,08:05 AM
56846,17,RMA,Ramganj Mandi,1827,09:43 AM,09:45 AM
56847,18,KOTA,Kota,1900,10:50 AM,11:00 AM
56848,19,SWM,Sawai Madhopur,2007,12:40 PM,12:55 PM
56849,20,DPA,Durgapura,2131,02:30 PM,02:33 PM
56850,21,JP,Jaipur,2139,02:50 PM,03:00 PM
56851,22,DKBJ,Dahar Ka Balaji,2142,03:10 PM,03:12 PM
56852,23,RGS,Ringas,2196,04:00 PM,04:05 PM
56853,24,SIKR,Sikar,2246,05:10 PM,05:15 PM
56854,25,NWH,Nawalgarh,2274,05:33 PM,05:35 PM
56855,26,JJN,Jhunjhunu,2310,06:02 PM,06:04 PM
56856,27,CRWA,Chirawa,2339,06:33 PM,06:35 PM
56857,28,LHU,Loharu,2368,07:35 PM,07:38 PM
56858,29,SDLP,Sadulpur,2418,08:35 PM,09:05 PM
56859,30,HSR,Hisar,2488,10:25 PM,10:25 PM

In [17]:
# Compare the observed stations against the route stations
for train_id in problem_trains:
    observed = set(
        delays.loc[
            delays["train"].astype(str) == train_id,
            "station"
        ].unique()
    )

    route_stations = set(
        routes.loc[
            routes["trainNumber"].astype(str) == train_id,
            "station_code"
        ].unique()
    )

    print("\n" + "=" * 60)
    print("TRAIN:", train_id)
    print("Observed but NOT in route:", sorted(observed - route_stations))
    print("Route but NOT observed:", sorted(route_stations - observed))

============================================================
TRAIN: 13212
Observed but NOT in route: ['TMA']
Route but NOT observed: []

============================================================
TRAIN: 20978
Observed but NOT in route: ['KSG']
Route but NOT observed: []

============================================================
TRAIN: 20952
Observed but NOT in route: ['KWP']
Route but NOT observed: []

============================================================
TRAIN: 4718
Observed but NOT in route: ['OGL']
Route but NOT observed: []

In [18]:
# ==========================================
# STEP 6: RECONSTRUCT ACTUAL DATETIMES
# ==========================================

import pandas as pd

# Work on a copy
ts = journey.copy()

# Convert service date
ts["service_date"] = pd.to_datetime(ts["date"], errors="coerce")

# Convert time strings to time-of-day
ts["actual_arr_time"] = pd.to_datetime(
    ts["act_arr"],
    format="%I:%M %p",
    errors="coerce"
).dt.time

ts["actual_dep_time"] = pd.to_datetime(
    ts["act_dep"],
    format="%I:%M %p",
    errors="coerce"
).dt.time

ts["scheduled_arr_time"] = pd.to_datetime(
    ts["sch_arr"],
    format="%I:%M %p",
    errors="coerce"
).dt.time

ts["scheduled_dep_time"] = pd.to_datetime(
    ts["sch_dep"],
    format="%I:%M %p",
    errors="coerce"
).dt.time

print("Time conversion complete.")

Time conversion complete.

In [19]:
# ==========================================
# STEP 7: HANDLE MIDNIGHT CROSSINGS
# ==========================================

def build_timestamp(date_series, time_series):
    return pd.to_datetime(
        date_series.astype(str) + " " + time_series.astype(str),
        errors="coerce"
    )

ts["actual_arr_dt"] = build_timestamp(
    ts["service_date"],
    ts["actual_arr_time"]
)

ts["actual_dep_dt"] = build_timestamp(
    ts["service_date"],
    ts["actual_dep_time"]
)

ts["scheduled_arr_dt"] = build_timestamp(
    ts["service_date"],
    ts["scheduled_arr_time"]
)

ts["scheduled_dep_dt"] = build_timestamp(
    ts["service_date"],
    ts["scheduled_dep_time"]
)

In [20]:
# ==========================================
# STEP 8: SHIFT TIMES AFTER MIDNIGHT
# ==========================================

def fix_midnight(group):
    group = group.sort_values("stnSerialNumber").copy()

    time_columns = [
        "actual_arr_dt",
        "actual_dep_dt",
        "scheduled_arr_dt",
        "scheduled_dep_dt"
    ]

    for col in time_columns:
        # Move timestamp forward by one day whenever it
        # would otherwise move backwards.
        values = group[col].tolist()

        for i in range(1, len(values)):
            if pd.notna(values[i]) and pd.notna(values[i-1]):
                while values[i] < values[i-1]:
                    values[i] += pd.Timedelta(days=1)

        group[col] = values

    return group


ts = (
    ts.groupby(["train", "date"], group_keys=False)
      .apply(fix_midnight)
      .reset_index(drop=True)
)

print("Midnight correction complete.")

C:\Users\Dell\AppData\Local\Temp\ipykernel_14396\35728505.py:32: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(fix_midnight)

Midnight correction complete.

In [21]:
check = ts[
    (ts["train"] == "12303") &
    (ts["date"] == "2024-09-02")
].sort_values("stnSerialNumber")

display(
    check[
        [
            "station",
            "stnSerialNumber",
            "actual_arr_dt",
            "actual_dep_dt",
            "arr_delay"
        ]
    ].tail(10)
)

,station,stnSerialNumber,actual_arr_dt,actual_dep_dt,arr_delay
146111,DNR,16.0,2024-09-02 16:46:00,2024-09-02 16:48:00,23.0
146112,ARA,17.0,2024-09-02 17:15:00,2024-09-02 17:20:00,23.0
146113,BXR,18.0,2024-09-02 18:01:00,2024-09-02 18:03:00,21.0
146114,DDU,19.0,2024-09-02 19:31:00,2024-09-02 19:41:00,0.0
146115,PRYJ,20.0,2024-09-02 21:43:00,2024-09-02 21:48:00,3.0
146116,CNB,21.0,2024-09-03 00:28:00,2024-09-03 00:33:00,26.0
146117,ETW,22.0,2024-09-03 02:16:00,2024-09-03 02:18:00,47.0
146118,TDL,23.0,2024-09-03 03:12:00,2024-09-03 03:14:00,24.0
146119,ALJN,24.0,2024-09-03 04:00:00,2024-09-03 04:02:00,22.0
146120,NDLS,25.0,2024-09-03 06:05:00,2024-09-03 06:05:00,0.0